### ISSUE TITLE
Help on overview of the package 

### ISSUE THREAD

**Issue by Kosakaruri** [georgewoolsey/point_cloud_tree_detection_ex#1]
Hi George,

My name is Jiawei Li, and I’m a postdoc working at USDA-ARS.
I had a meeting with Wade this Monday and I'm very excited about this project and would like to contribuate in the furture. 
I'm looking through the code right now. I would like to learn from you about the detail of your work and hope to participate. Could we schedule a meeting in the coming two weeks?

Thanks,

Jiawei

**Comment by georgewoolsey** [comment]
Hi @Kosakaruri -- I would be happy to discuss some of this work. If you are on USDA then you can reach me at george.woolsey@usda.gov and my calendar is mostly up-to-date on there if you wanted to schedule some time for us.
